os: windows 
language: shell
before_install:
        - choco install python
install:
  # upgrade pip
  - pip install --upgrade pip
  # install pypresence
  - pip install -U pypresence
  # install gd.py
  - pip install -U gd.py
  # install asyncio
  - pip install -U asyncio
  # install pyinstaller
  - pip install -U pyinstaller

script:
  - python -m PyInstaller -F --hiddenimport pkg_resources.py2_warn -i gd.ico pygdrpc.py
  - sleep 1  # Allow pyinstaller to finish writing to stdout
  - ls -l dist
  - dist/pygdrpc.exe
