language: shell

python:
  - "3.7"
  - "3.8"
os: windows
before_install:
  - choco install python
install:
  # upgrade pip
  - python -m pip install --upgrade pip
  # install pypresence
  - python -m pip install -U pypresence
  # install gd.py
  - python -m pip install -U gd.py
  # install asyncio
  - python -m pip install -U asyncio
  # install pyinstaller
  - python -m pip install -U pyinstaller

script:
  - python -m PyInstaller -F --hiddenimport pkg_resources.py2_warn -i gd.ico pygdrpc.py
  - sleep 1  # Allow pyinstaller to finish writing to stdout
  - ls -l dist
  - dist/pygdrpc.exe
